### ISSUE TITLE
Support spiral/roadrunner-http:^3.0.0

### ISSUE THREAD

**Issue by mingalevme** [roadrunner-php/laravel-bridge#125]
Current version of the `laravel-bridge` does not support latest versions of `spiral/roadrunner-http`: https://github.com/roadrunner-php/laravel-bridge/blob/f9337ac5727cc42df78f5c54e71d621a55fb123b/composer.json#L22

Please, add support for `spiral/roadrunner-http:^3.0`.

**Comment by tarampampam** [comment]
Thanks for your issue! Could you test the changes in https://github.com/roadrunner-php/laravel-bridge/pull/126 on your side?
