### ISSUE TITLE
Premission Denied

### ISSUE THREAD

**Issue by UtkuDalmaz** [roadrunner-php/laravel-bridge#129]
RuntimeException 

  Cannot reload RoadRunner: sh: 1: exec: : Permission denied

  at /var/www/site/public_html/vendor/laravel/octane/src/RoadRunner/ServerProcessInspector.php:54
     50▕             '-o', "rpc.listen=tcp://$host:$rpcPort",
     51▕             '-s',
     52▕         ], base_path()))->start()->waitUntil(function ($type, $buffer) {
     53▕             if ($type === Process::ERR) {
  ➜  54▕                 throw new RuntimeException('Cannot reload RoadRunner: '.$buffer);
     55▕             }
     56▕ 
     57▕             return true;
     58▕         });

      [2m+29 vendor frames [22m

I am getting this error when I use --watch flag with octane:start and save a file 

Any idea?

**Comment by tarampampam** [comment]
Maybe ask this question in the octane repository?
